name: testing

on:
  push:
    branches:
      - "main"
    paths:
      - "src/**/*"
      - "tests/**/*"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - ".github/workflows/testing.yml"
  pull_request:
    branches:
      - "main"
    paths:
      - "src/**/*"
      - "tests/**/*"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - ".github/workflows/testing.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        env:
          NSS_WRAPPER_PASSWD: tests/fixtures/passwd
          NSS_WRAPPER_GROUP: tests/fixtures/group
        run: |
          sudo apt update && sudo apt install -y libnss-wrapper
          cargo test
          LD_PRELOAD=libnss_wrapper.so cargo test --features test-integration mocked_
          LD_PRELOAD=libnss_wrapper.so cargo test --features test-integration --test '*'

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Generate code coverage
        run: |
          cargo tarpaulin --verbose --workspace
